import { Playfair_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${playfair.variable} ${sourceSans.variable} antialiased`}>
        <Nav />
        <main className="container">
          {children}
        </main>
      </body>
    </html>
  );
}
